In [1]:
%autosave 30

Autosaving every 30 seconds

In [6]:
# Employee Technology Training Data - Version 01 - Iteration 02

import xlrd
wb = xlrd.open_workbook("02-EmployeeTrainingData-Complete.xlsx")
ws = wb.sheet_by_index(0)
print ("Employees Training Data - Location:", wb.sheet_names()) # Store in a list and print it with help of index number.

# List1 appends replaces empty spaces with 'INVALID' and List2 is nested list of each record with all colums
myList1 = []
myList2 = []
for j in range(0, ws.nrows):
    for i in range(0, ws.ncols):
        if ws.cell_value(j, i) == '':
            myList1.append("INVALID")
        else:
            myList1.append(str(ws.cell_value(j, i)))
    myList2.append(myList1)
    myList1 = []

# List3 is a collection of all values in nested lists of List2 
myList3 = []
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        myList3.append(myList2[i][j])

# List4 is collection of string lengths of all values of List3
myList4 = []
for i in range (0, len(myList3)):
    myList4.append(len(str(myList3[i])))

# Following code is right justifying all the values in List4
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        if len(myList2[i][j]) < max(myList4):
            tempStrLen = max(myList4) - 1
            print (tempStrLen)
        # print (myList2[i][j].rjust(tempStrLen))
    # print ("\n")

Employees Training Data - Location: ['Bangalore', 'Noida&Others', 'Chennai', 'Pune', 'Mumbai']
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28

In [40]:
# List3 is a collection of all values in nested lists of List2 
myList3 = []
for i in range (0, ws.nrows):
#     for j in range (0, ws.ncols):
        myList3.append(myList2[i][0])
# print (myList3)

# List4 is collection of string lengths of all values of List3
myList4 = []
for i in range (0, len(myList3)):
    myList4.append(len(str(myList3[i])))


for i in range (0, ws.nrows):
#    for j in range (0, ws.ncols):
        if len(myList2[i][0]) < max(myList4):
            # tempStrLen = max(myList4) - len(myList2[i][0]) # 1
            tempStrLen = len(myList2[i][0]) - max(myList4) # 1
            # print (tempStrLen)
        print (myList2[i][0].rjust(tempStrLen, '.'))
        # print (str(myList2[i][0].rjust(tempStrLen)))
        # print (type(myList2[i][0].rjust(tempStrLen)))
    # print ("\n")

Employee Id
143184
46013981
46016940
143700
168943
165439
149286
147673
46002548
46001193
46001193
46013986
144980
156950
163243
151097
115949
119618
168944
46001093
68149
168965
75029
159884
117612
168541
116244
46004786
122597
115569
46001171
167469
162835
46018744
46001213
46010556
46001212
46001192
143655
176838
46020214
191231
118772
152095
168946
144129
46018505
156808
174091
avsheth
46022732
147673
176111
169341
140461
143184
175212
23028
168919
120520
46018816
46012480
159885
46004137
168919
094381
124701
126631
46002410
173791
143168
115175.0

In [54]:
# print (myList2)
for i in range (0, ws.nrows):
    print (myList2[i][0].rjust(12, ' '), "\t", myList2[i][1].ljust(24, ' '), "\t",)

 Employee Id 	 Name
      143184 	 Kamelia Sinha
    46013981 	 Raj kumar
    46016940 	 M venu
      143700 	 pratap pokala
      168943 	 Korrapati Pavitra Kumari
      165439 	 Abhinava Y R
      149286 	 Sridharan
      147673 	 RAJESH PRABHU MANGALORE
    46002548 	 Neeraj Kumar Prajapati
    46001193 	 Akshdeep kaur sidhu
    46001193 	 Akshdeep kaur sidhu
    46013986 	 sekhar kishorekumar
      144980 	 Y Sasivardhan Reddy
      156950 	 Varun R
      163243 	 Mudhireddy Surekha
      151097 	 Shreemudra Satapathy
      115949 	 vishal rai
      119618 	 Senthil Shanmugam
      168944 	 Lohithashree P S
    46001093 	 vishal bansal
       68149 	 Venkataramanarao
      168965 	 Mounika Narla
       75029 	 Aditi Sharma
      159884 	 Valmiki Sai Puneeth
      117612 	 Ritu Agrawal
      168541 	 Lavanya KS
      116244 	 Adarsh Valamary
    46004786 	 Sathyanarayana L J
      122597 	 Prajwala tarugu
      115569 	 Syed Roshan
    46001171 	 Argha Boksi
      167469 	 Swathi Umesh Naik
      162835 	 Karthik Devaraj
    46018744 	 Garlapati Mohan
    46001213 	 Pushan Banerjee
    46010556 	 Sai Vamshi Krishna Nama
    46001212 	 Kasu Narsimharaj
    46001192 	 Shirin Shaw
      143655 	 Venkata kumar
      176838 	 Vinod K
    46020214 	 Gowsick Ragupathi
      191231 	 Rineesh Babu
      118772 	 Samyuktha Tamatam
      152095 	 Soniya Asati
      168946 	 Syed Irfan Rizvi
      144129 	 Aravind Keelapatta
    46018505 	 Dindukurthi Sai Jayanth Kumar
      156808 	 Vamsi Krishna
      174091 	 Monisha Shanil
     avsheth 	 Avni
    46022732 	 Gururaja CS
      147673 	 Rajesh Prabhu Mangalore
      176111 	 Lal Sahab
      169341 	 Sandhya Prasanna
      140461 	 Mukesh kumar singh
      143184 	 Kamelia Sinha
      175212 	 Abhishek Kumar
       23028 	 srinivasa rao dasari
      168919 	 kunapareddy praneeth
      120520 	 Lakshmi kumari Ekula
    46018816 	 Yogendra cp
    46012480 	 Jayanthrowth C V
      159885 	 Abhishek Shukla
    46004137 	 Rajesh Kumar Pradhan
      168919 	 kunapareddy praneeth
      094381 	 Sowmya
      124701 	 Chandradhar S Gujjalar
      126631 	 Seema
    46002410 	 Aneela Ammu Thomas
      173791 	 SIBBIR AHMED
      143168 	 Geet Sethi
    115175.0 	 Yatheesh Valakadama

In [78]:
# Following code is not complete, hence not to be executed
"""
myList01 = [1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111]
myList02 = ['a', 'aa', 'aaa', 'aaaa', 'aaaaa', 'aaaaaa'. 'aaaaaaa', 'aaaaaaaa', 'aaaaaaaaa']
for eachElement in myList01:
    print (myList01.rjust())
"""

"\nmyList01 = [1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111]\nmyList02 = ['a', 'aa', 'aaa', 'aaaa', 'aaaaa', 'aaaaaa'. 'aaaaaaa', 'aaaaaaaa', 'aaaaaaaaa']\nfor eachElement in myList01:\n    print (myList01.rjust())\n"

In [75]:
# myListEID = []
mySetCL = set()
# print (myList2)
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        # myListEID.append(len(myList2[i][0]))
        # print (mySetCL.add (len(myList2[i][0]))) # This will not result in any meaningful result
        mySetCL.add (len(myList2[i][0]))
    # count += 1
    # print (len(myList2[i][0]))
    # print (count)
# print (myListEID)
print (mySetCL)

{5, 6, 7, 8, 11}

In [79]:
mySetCL = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetCL.add (len(myList2[i][0]))
print (max(mySetCL))

11

In [94]:
# May be we can code a function to help us with max length of values in each column,
# Data Type: Integer/Flaot/String - really does not matter
# Code to 
mySetEID = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetEID.add (len(myList2[i][0]))
# print (max(mySetEID))

mySetNAME = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetNAME.add (len(myList2[i][1]))
# print (max(mySetNAME))

mySetAng6 = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetAng6.add (len(myList2[i][2]))
# print (max(mySetAng6))

mySetAng7 = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetAng7.add (len(myList2[i][3]))
# print (max(mySetAng7))

mySetAng8 = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetAng8.add (len(myList2[i][4]))
# print (max(mySetAng8))

mySetJquery = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetJquery.add (len(myList2[i][5]))
# print (max(mySetJquery))

mySetTS = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetTS.add (len(myList2[i][6]))
# print (max(mySetTS))

mySetNJS = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetNJS.add (len(myList2[i][7]))
# print (max(mySetNJS))

mySetRJS = set()
count = 0
for i in range (0, ws.nrows):
    for j in range (0, ws.ncols):
        mySetRJS.add (len(myList2[i][7]))
# print (max(mySetRJS))

# print (myList2)
for i in range (0, ws.nrows):
    # print (myList2[i][0].rjust(max(mySetEID), ' '), "\t", myList2[i][1].ljust(24, ' '), "\t",)
    print (myList2[i][0].rjust(max(mySetEID), ' '), myList2[i][1].ljust(max(mySetNAME), ' '), \
           myList2[i][2].ljust(max(mySetAng6), ' '), myList2[i][3].ljust(max(mySetAng7), ' '), \
           myList2[i][4].ljust(max(mySetAng8), ' '), myList2[i][5].ljust(max(mySetJquery), ' '), \
           myList2[i][6].ljust(max(mySetTS), ' '), myList2[i][7].ljust(max(mySetNJS), ' '), \
           myList2[i][8].ljust(max(mySetRJS), ' '))
    # print (myList2[i][0].rjust(max(mySetEID)))

Employee Id Name                          Angular-6 Angular-7 Angular-8  Jquery    Typescript NodeJS    ReactJS
     143184 Kamelia Sinha                 INVALID   INVALID   July       INVALID   INVALID    November  October
   46013981 Raj kumar                     INVALID   INVALID   INVALID    INVALID   INVALID    August    July
   46016940 M venu                        July      July      August     July      July       August    August
     143700 pratap pokala                 INVALID   INVALID   INVALID    INVALID   December   December  November
     168943 Korrapati Pavitra Kumari      INVALID   INVALID   INVALID    INVALID   INVALID    September July
     165439 Abhinava Y R                  August    August    September  INVALID   September  October   October
     149286 Sridharan                     July      August    August     July      July       September September
     147673 RAJESH PRABHU MANGALORE       December  INVALID   July       INVALID   July       INVALID   July
   46002548 Neeraj Kumar Prajapati        August    INVALID   September  INVALID   INVALID    July      July
   46001193 Akshdeep kaur sidhu           July      INVALID   August     INVALID   July       INVALID   July
   46001193 Akshdeep kaur sidhu           INVALID   INVALID   August     September July       October   July
   46013986 sekhar kishorekumar           INVALID   INVALID   INVALID    INVALID   September  August    July
     144980 Y Sasivardhan Reddy           July      August    August     July      September  INVALID   September
     156950 Varun R                       INVALID   INVALID   October    INVALID   September  July      August
     163243 Mudhireddy Surekha            November  October   September  INVALID   INVALID    August    July
     151097 Shreemudra Satapathy          INVALID   INVALID   INVALID    September September  July      August
     115949 vishal rai                    September September August     INVALID   July       August    July
     119618 Senthil Shanmugam             July      October   December   INVALID   August     September November
     168944 Lohithashree P S              INVALID   INVALID   INVALID    INVALID   INVALID    INVALID   July
   46001093 vishal bansal                 December  November  October    August    September  August    July
      68149 Venkataramanarao              September October   November   July      August     December  August
     168965 Mounika Narla                 July      August    August     August    July       September August
      75029 Aditi Sharma                  July      July      August     August    September  October   November
     159884 Valmiki Sai Puneeth           August    September October    July      July       September August
     117612 Ritu Agrawal                  September October   November   December  August     July      August
     168541 Lavanya KS                    July      July      July       August    July       September INVALID
     116244 Adarsh Valamary               INVALID   INVALID   August     INVALID   July       INVALID   September
   46004786 Sathyanarayana L J            December  October   INVALID    August    July       August    July
     122597 Prajwala tarugu               July      August    October    INVALID   September  December  August
     115569 Syed Roshan                   INVALID   INVALID   INVALID    July      INVALID    July      July
   46001171 Argha Boksi                   INVALID   INVALID   INVALID    INVALID   INVALID    July      August
     167469 Swathi Umesh Naik             October   October   October    November  December   August    September
     162835 Karthik Devaraj               July      August    September  INVALID   November   December  October
   46018744 Garlapati Mohan               July      July      July       August    July       August    September
   46001213 Pushan Banerjee               November  November  July       November  August     August    August
   46010556 Sai Vamshi Krishna Nama       INVALID   INVALID   INVALID    INVALID   August     July      INVALID
   46001212 Kasu Narsimharaj              December  August    September  July      October    August    November
   46001192 Shirin Shaw                   INVALID   INVALID   INVALID    INVALID   INVALID    INVALID   July
     143655 Venkata kumar                 July      August    September  October   August     November  December
     176838 Vinod K                       INVALID   INVALID   August     INVALID   INVALID    INVALID   October
   46020214 Gowsick Ragupathi             INVALID   INVALID   INVALID    INVALID   August     September July
     191231 Rineesh Babu                  INVALID   INVALID   INVALID    INVALID   INVALID    July      July
     118772 Samyuktha Tamatam             September October   November   December  August     July      December
     152095 Soniya Asati                  July      July      August     October   July       August    August
     168946 Syed Irfan Rizvi              September October   December   July      September  August    July
     144129 Aravind Keelapatta            July      INVALID   July       August    July       July      August
   46018505 Dindukurthi Sai Jayanth Kumar September July      July       July      September  October   November
     156808 Vamsi Krishna                 INVALID   INVALID   August     INVALID   September  INVALID   October
     174091 Monisha Shanil                July      August    September  December  July       November  October
    avsheth Avni                          July      August    September  INVALID   July       September October
   46022732 Gururaja CS                   September September September  September August     August    August
     147673 Rajesh Prabhu Mangalore       INVALID   INVALID   INVALID    INVALID   July       July      July
     176111 Lal Sahab                     INVALID   INVALID   August     October   August     September September
     169341 Sandhya Prasanna              INVALID   INVALID   November   September October    July      August
     140461 Mukesh kumar singh            INVALID   INVALID   INVALID    INVALID   INVALID    July      INVALID
     143184 Kamelia Sinha                 INVALID   INVALID   July       October   August     INVALID   November
     175212 Abhishek Kumar                July      August    September  INVALID   October    November  December
      23028 srinivasa rao dasari          August    September October    INVALID   August     August    September
     168919 kunapareddy praneeth          November  October   July       INVALID   December   September August
     120520 Lakshmi kumari Ekula          August    September October    INVALID   July       November  July
   46018816 Yogendra cp                   August    July      July       September September  October   October
   46012480 Jayanthrowth C V              INVALID   December  August     November  October    July      September
     159885 Abhishek Shukla               August    September October    July      July       November  December
   46004137 Rajesh Kumar Pradhan          INVALID   INVALID   August     INVALID   INVALID    July      INVALID
     168919 kunapareddy praneeth          INVALID   INVALID   July       November  October    September August
     094381 Sowmya                        August    August    August     July      July       September September
     124701 Chandradhar S Gujjalar        August    September October    November  July       December  December
     126631 Seema                         July      July      July       July      July       July      July
   46002410 Aneela Ammu Thomas            July      INVALID   INVALID    July      July       INVALID   July
     173791 SIBBIR AHMED                  November  November  October    December  July       August    September
     143168 Geet Sethi                    July      INVALID   September  INVALID   November   August    December
   115175.0 Yatheesh Valakadama           INVALID   INVALID   October    INVALID   September  November  December

In [142]:
import xlrd
wb = xlrd.open_workbook("02-EmployeeTrainingData-Complete.xlsx")
ws = wb.sheet_by_index(0)

def myGenFunc(a):
    myGenSet = set()
    count = 0
    for i in range (0, ws.nrows):
        for j in range (0, ws.ncols):
            myGenSet.add (len(myList2[i][a]))
    return (max(myGenSet))
    # return max(myGenSet)
# print (max(mySetNJS))
myGenFunc(0)
for i in range (0, ws.nrows):
    print (myList2[i][0].rjust(myGenFunc(0), ' '), myList2[i][1].ljust(myGenFunc(1), ' '), \
           myList2[i][2].ljust(myGenFunc(2), ' '), myList2[i][3].ljust(myGenFunc(3), ' '), \
           myList2[i][4].ljust(myGenFunc(4), ' '), myList2[i][5].ljust(myGenFunc(5), ' '), \
           myList2[i][6].ljust(myGenFunc(6), ' '), myList2[i][7].ljust(myGenFunc(7), ' '), \
           myList2[i][8].ljust(myGenFunc(8), ' '))

Employee Id Name                          Angular-6 Angular-7 Angular-8  Jquery    Typescript NodeJS    ReactJS
     143184 Kamelia Sinha                 INVALID   INVALID   July       INVALID   INVALID    November  October
   46013981 Raj kumar                     INVALID   INVALID   INVALID    INVALID   INVALID    August    July
   46016940 M venu                        July      July      August     July      July       August    August
     143700 pratap pokala                 INVALID   INVALID   INVALID    INVALID   December   December  November
     168943 Korrapati Pavitra Kumari      INVALID   INVALID   INVALID    INVALID   INVALID    September July
     165439 Abhinava Y R                  August    August    September  INVALID   September  October   October
     149286 Sridharan                     July      August    August     July      July       September September
     147673 RAJESH PRABHU MANGALORE       December  INVALID   July       INVALID   July       INVALID   July
   46002548 Neeraj Kumar Prajapati        August    INVALID   September  INVALID   INVALID    July      July
   46001193 Akshdeep kaur sidhu           July      INVALID   August     INVALID   July       INVALID   July
   46001193 Akshdeep kaur sidhu           INVALID   INVALID   August     September July       October   July
   46013986 sekhar kishorekumar           INVALID   INVALID   INVALID    INVALID   September  August    July
     144980 Y Sasivardhan Reddy           July      August    August     July      September  INVALID   September
     156950 Varun R                       INVALID   INVALID   October    INVALID   September  July      August
     163243 Mudhireddy Surekha            November  October   September  INVALID   INVALID    August    July
     151097 Shreemudra Satapathy          INVALID   INVALID   INVALID    September September  July      August
     115949 vishal rai                    September September August     INVALID   July       August    July
     119618 Senthil Shanmugam             July      October   December   INVALID   August     September November
     168944 Lohithashree P S              INVALID   INVALID   INVALID    INVALID   INVALID    INVALID   July
   46001093 vishal bansal                 December  November  October    August    September  August    July
      68149 Venkataramanarao              September October   November   July      August     December  August
     168965 Mounika Narla                 July      August    August     August    July       September August
      75029 Aditi Sharma                  July      July      August     August    September  October   November
     159884 Valmiki Sai Puneeth           August    September October    July      July       September August
     117612 Ritu Agrawal                  September October   November   December  August     July      August
     168541 Lavanya KS                    July      July      July       August    July       September INVALID
     116244 Adarsh Valamary               INVALID   INVALID   August     INVALID   July       INVALID   September
   46004786 Sathyanarayana L J            December  October   INVALID    August    July       August    July
     122597 Prajwala tarugu               July      August    October    INVALID   September  December  August
     115569 Syed Roshan                   INVALID   INVALID   INVALID    July      INVALID    July      July
   46001171 Argha Boksi                   INVALID   INVALID   INVALID    INVALID   INVALID    July      August
     167469 Swathi Umesh Naik             October   October   October    November  December   August    September
     162835 Karthik Devaraj               July      August    September  INVALID   November   December  October
   46018744 Garlapati Mohan               July      July      July       August    July       August    September
   46001213 Pushan Banerjee               November  November  July       November  August     August    August
   46010556 Sai Vamshi Krishna Nama       INVALID   INVALID   INVALID    INVALID   August     July      INVALID
   46001212 Kasu Narsimharaj              December  August    September  July      October    August    November
   46001192 Shirin Shaw                   INVALID   INVALID   INVALID    INVALID   INVALID    INVALID   July
     143655 Venkata kumar                 July      August    September  October   August     November  December
     176838 Vinod K                       INVALID   INVALID   August     INVALID   INVALID    INVALID   October
   46020214 Gowsick Ragupathi             INVALID   INVALID   INVALID    INVALID   August     September July
     191231 Rineesh Babu                  INVALID   INVALID   INVALID    INVALID   INVALID    July      July
     118772 Samyuktha Tamatam             September October   November   December  August     July      December
     152095 Soniya Asati                  July      July      August     October   July       August    August
     168946 Syed Irfan Rizvi              September October   December   July      September  August    July
     144129 Aravind Keelapatta            July      INVALID   July       August    July       July      August
   46018505 Dindukurthi Sai Jayanth Kumar September July      July       July      September  October   November
     156808 Vamsi Krishna                 INVALID   INVALID   August     INVALID   September  INVALID   October
     174091 Monisha Shanil                July      August    September  December  July       November  October
    avsheth Avni                          July      August    September  INVALID   July       September October
   46022732 Gururaja CS                   September September September  September August     August    August
     147673 Rajesh Prabhu Mangalore       INVALID   INVALID   INVALID    INVALID   July       July      July
     176111 Lal Sahab                     INVALID   INVALID   August     October   August     September September
     169341 Sandhya Prasanna              INVALID   INVALID   November   September October    July      August
     140461 Mukesh kumar singh            INVALID   INVALID   INVALID    INVALID   INVALID    July      INVALID
     143184 Kamelia Sinha                 INVALID   INVALID   July       October   August     INVALID   November
     175212 Abhishek Kumar                July      August    September  INVALID   October    November  December
      23028 srinivasa rao dasari          August    September October    INVALID   August     August    September
     168919 kunapareddy praneeth          November  October   July       INVALID   December   September August
     120520 Lakshmi kumari Ekula          August    September October    INVALID   July       November  July
   46018816 Yogendra cp                   August    July      July       September September  October   October
   46012480 Jayanthrowth C V              INVALID   December  August     November  October    July      September
     159885 Abhishek Shukla               August    September October    July      July       November  December
   46004137 Rajesh Kumar Pradhan          INVALID   INVALID   August     INVALID   INVALID    July      INVALID
     168919 kunapareddy praneeth          INVALID   INVALID   July       November  October    September August
     094381 Sowmya                        August    August    August     July      July       September September
     124701 Chandradhar S Gujjalar        August    September October    November  July       December  December
     126631 Seema                         July      July      July       July      July       July      July
   46002410 Aneela Ammu Thomas            July      INVALID   INVALID    July      July       INVALID   July
     173791 SIBBIR AHMED                  November  November  October    December  July       August    September
     143168 Geet Sethi                    July      INVALID   September  INVALID   November   August    December
   115175.0 Yatheesh Valakadama           INVALID   INVALID   October    INVALID   September  November  December